- name: Domain Controller Config
  hosts: servers
  vars_prompt:
    - name: password
      prompt: Enter new local admin password 
      private: true
  tasks:
    - name: set new local admin password
      ansible.windows.win_user:
        name: Administrator
        password: "{{ password }}"
        password_expired: false
        update_password: always
    - name: set hostname
      ansible.windows.win_hostname:
        name: "{{ hostname }}"
    - name: reboot
      ansible.windows.win_reboot:
    - name: new forest
      ansible.windows.win_domain:
        dns_domain_name: "{{ domain }}"
        safe_mode_password: "{{ password }}"
      register: domain_install
    - debug:
        var: domain_install
    - name: reboot2
      ansible.windows.win_reboot:
    - name: add DNS forwarder
      ansible.windows.win_shell: Add-DnsServerForwarder -IPAddress 10.0.5.2
    - name: move script
      ansible.builtin.copy:
        src: ./files/winServer/ou.ps1.j2
        dest: C:\Users\Administrator\ou.ps1
    - name: make OU structure
      ansible.windows.win_shell: C:\Users\Administrator\ou.ps1