- name: Debian Splunk Agent Install
  hosts: 10.0.5.30
  tasks:
  - name: create group splunkfwd
    become: true
    ansible.builtin.group:
      name: splunkfwd
      state: present
  - name: make splunkfwd user
    become: true
    ansible.builtin.user:
      name: splunkfwd
      group: splunkfwd
  - name: make splunk home directory
    become: true
    ansible.builtin.file:
      path: /opt/splunkforwarder/etc/system/local/
      state: directory
      recurse: true
  - name: create user account
    become: true
    ansible.builtin.copy:
      src: files/user-seed.conf.j2
      dest: /opt/splunkforwarder/etc/system/local/user-seed.conf
  - name: download splunk forwarder
    ansible.builtin.get_url:
      url: https://download.splunk.com/products/universalforwarder/releases/9.4.1/linux/splunkforwarder-9.4.1-e3bdab203ac8-linux-amd64.deb
      dest: /home/deployer/splunkForwarderInstaller.deb
      mode: '664'
  - name: dpkg and install splunk forwarder
    become: true
    ansible.builtin.apt:
      deb: /home/deployer/splunkForwarderInstaller.deb
  - name: set permisions and start
    become: true
    ansible.builtin.shell: |
      chown -R splunkfwd:splunkfwd /opt/splunkforwarder 
      cd /opt/splunkforwarder/bin && ./splunk start --accept-license --no-prompt --answer-yes
      cd /opt/splunkforwarder/bin && ./splunk add forward-server 10.0.5.32:9997
  - name: add monitor
    become: true
    ansible.builtin.expect:
      command: /opt/splunkforwarder/bin/splunk add monitor /var/log
      responses: 
        "Splunk username":
          - "{{ user }}"
        "Password":
          - "{{ pass }}"
 