- name: vyos network config
  hosts: vyos
  vars_prompt:

  - name: password
    prompt: Enter your new VYOS password
    private: true
  tasks:
    - local_action: ansible.builtin.shell mkpasswd -m sha-512 {{ password }}
      register: hash
    - name: "check hash format"
      ansible.builtin.debug:
        msg: hash {{ hash.stdout }}
    - name: load vyos config from template
      become: yes
      template: 
        src: files/vyos/config.boot.j2
        dest: /config/config.boot
        mode: "0775"
        owner: root
        group: vyattacfg
    - name: reboot
      become: yes
      shell: nohup bash -c "/usr/bin/sleep 5 && /usr/sbin/shutdown -r now" &